### ISSUE TITLE
What is feature transformation net?

### ISSUE THREAD

**Issue by MyeongJin-Kim** [RogerZhangzz/CAG_UDA#3]
you said on paper "the decoder can be further divided in to a feature transformation net and a classifier"

In my thought, ASPP is classifier which is layer5 in this code. But I don't know what is feature transformation net.

![11950891-0631-41EB-9734-687AFEFC4DAF](https://user-images.githubusercontent.com/39029444/69839350-8262d480-129a-11ea-9ba0-af0398ecb530.png)

**Comment by RogerZhangzz** [comment]
Hi,

ASPP module is embedded in 'self.layer5' from your code if there's no misunderstanding, and there are a set of layers (conv layers, relu layers, etc.) in 'self.layer5'. Actually, the 'classifier' I mentioned in the paper refers to only the last convolution layer. The features which are used to calculate 'anchors' (after 'f_D') are those just before the last convolution layer.

So maybe you need to decomposite 'self.layer5' to better understand the CAG method.

**Comment by MyeongJin-Kim** [comment]
Thanks for response!

This code is from AdaptSegNet
https://github.com/wasidennis/AdaptSegNet/blob/master/model/deeplab.py

<img width="922" alt="image" src="https://user-images.githubusercontent.com/39029444/69892754-48520b00-134c-11ea-82d2-9514dea7b3c2.png">

In this code, layer 5 only consists of ASPP.
Is this different from your decoder part?

**Comment by RogerZhangzz** [comment]
Hi, sorry for the delay. There are some differences in the way of implementation from mine. But you can still implement the CAG method in your code if you want, and I'm quite sure you will see a performance increase.

**Comment by MyeongJin-Kim** [comment]
Thanks! When will be the code be released?
