### ISSUE TITLE
GTA5/split.mat

### ISSUE THREAD

**Issue by cuishuhao** [RogerZhangzz/CAG_UDA#5]
Thanks for your job.
When I try to reproduce your job by running 'train.py', I could not find the file of 'GTA5/split.mat'. I could not find it in GTA5, and could you share the file?

**Comment by RogerZhangzz** [comment]
Hi,

Just go to the website for the GTA5 dataset. 'https://download.visinf.tu-darmstadt.de/data/from_games/'
Then searching 'split' as the keyword, you would find the file. It is released via a link in the paragraph of 'Data'.
Or just annotate the code of loading 'split.mat' in 'gta5_dataset.py: 72'. The split file is not necessary to reproduce the CAG method.
Plz notice that there are some updates five days before to fix some bugs.

Thanks.

**Comment by cuishuhao** [comment]
Thank you. It is solved.
